### PR TITLE
clear invalid file refs when uploading new zip

### LINKED ISSUE #153: Clearing files should clear files
Clearing exam files should clear referenced Q, P files and CodeTag references in the exam editor.

### PR DESCRIPTION
**Pull request by kylesferrazza**
closes #153

### CODE REVIEW

**Comment by kylesferrazza** [comment]
When uploading a new file, the effect gets triggered and removes any refs that no longer exist.

**Comment by blerner** [comment]
I don't understand the use of the `useEffectSkipFirst` -- what are you trying to achieve there?  (Leave a comment explaining it, so I'll remember when next I look at it.)

Minor nitpick: if I change the files, and then click the Reset button, the file-uploader says "Choose a file" instead of the "Saved files" it started from.

**Comment by kylesferrazza** [comment]
We don’t want the effect to fire on the first render, just the first time the dependencies change (we assume the refs from the database are correct and don’t need immediate filtering). I’ll add a comment to the code to explain it. 

Re the nitpick: clearing files actually clears them, doesn’t reset to the old value. So the picker is empty and the prof would have to choose a new file to populate it again.

**Comment by blerner** [comment]
Ok, so the suppressing-the-first-render effect is just for efficiency?

As for the reset, that seems surprising to me, especially since clicking Reset and then clicking "Preview # files" does indeed show the original files, and I can choose among those files for other exam/question/part file-pickers.  So do you mean that literally only the "Choose a file" upload picker is empty, or really all the files are empty?  It seems only the former, and if so, then it really should say "Saved files" again.

**Comment by kylesferrazza** [comment]
Ah, you meant (and said) the reset button. 

I thought you meant the clear files button.

**Pull request merged**
