### PR TITLE
Fix #334

### LINKED ISSUE #334: Make start and end times linkable
image

Should be able to set the start time in the future and have the end time update too, preserving the duration.

Photo with "chain-link" UI for reference

### PR DESCRIPTION
**Pull request by blerner**

### CODE REVIEW

**Comment by blerner** [comment]
image

When the times are linked, changing one time will offset the other to preserve the duration between them.  When the times aren't linked, changing either time will leave the other unchanged, _unless_ `endTime < startTime`, in which case they'll be set to the same time.

**Comment by kylesferrazza** [comment]
Code and screenshot look good! I am going to try it out locally now.

Is this PR supposed to include the first commit related to rubrics?

**Comment by kylesferrazza** [comment]
- unlink
- set start and end three days apart
- link
- set start day after end
Start and end times end up the same, and duration is not preserved.

**Comment by blerner** [comment]
Correct. I didn't account for duration when the endpoints cross over. I
hadn't decided whether that was needed, or whether that simply wouldn't
cause any confusion to professors. We'd typically want to change both
endpoints manually, and the duration is a transient value while we'd be
editing...

**Comment by kylesferrazza** [comment]
I just did not expect the start and end times to become the same when I changed the date of the exam

**Comment by blerner** [comment]
I mean, I said exactly that in the comment above :-) But it shouldn't be hard to include the duration when revising the endpoints when they cross over each other.

**Comment by blerner** [comment]
This can be rebased onto the main branch; the fix for rubrics is logically independent of this. (Still needed, though, but separate from this.)

**Review by kylesferrazza — APPROVED** [review]

**Pull request merged**
