### PR TITLE
Fix #71

### LINKED ISSUE #71: Simplify the UI when a question has only one part
We don't need to render Question 1 > Part 1, when there is only one part to a question...  (This affects the jump table, the rendering of `<Question>`, and potentially the rendering of `<Part>`.)

### PR DESCRIPTION
**Pull request by blerner**
closes #71

### CODE REVIEW

**Comment by kylesferrazza** [comment]
Scrollspies for anonymous parts are broken, since they try to spy their part number, which is no longer in `spyCoords`.

**Comment by blerner** [comment]
It should suffice then to just comment out the Top/BottomScrollSpies when the part is anonymous, right?

**Comment by kylesferrazza** [comment]
Yes, I think so.

**Comment by kylesferrazza** [comment]
We should test `separateSubparts` with a single part - there may be some interesting errors.

For example, when `separateSubparts` is on, we currently have a paginated question's scrollspy spy for the part, which could lead to the same error we saw above.

**Comment by blerner** [comment]
Maybe, but I'd be happy making that a exam-well-formedness error when we upload the exam.yaml file.

**Comment by kylesferrazza** [comment]
closes #71

**Pull request merged**
