### PR TITLE
use redis for actioncable

### PR DESCRIPTION
**Pull request by kylesferrazza**

### CODE REVIEW

**Comment by kylesferrazza** [comment]
For running in development, I was able to just run `redis-server` in another terminal, and everything Just Worked:tm:.

**Comment by blerner** [comment]
Should all the channel prefixes be "production"??

**Comment by kylesferrazza** [comment]
> Should all the channel prefixes be "production"??

Fixed right before this comment :)

**Comment by kylesferrazza** [comment]
- [ ] needs rebase

**Pull request closed without merging**
