### PR TITLE
Allow blank points input

### PR DESCRIPTION
**Pull request by tmazeika**
Allow points fields to receive blank input, and not force it to display `0`.

### CODE REVIEW

**Comment by tmazeika** [comment]
Right now, when you hit backspace in an input field with one digit, it goes back a page in the browser's history instead of clearing the input.

**Comment by blerner** [comment]
@tmazeika this PR is obsolete now, right?  We've fixed this elsewhere?

**Comment by tmazeika** [comment]
@blerner I'm still getting an Internal Server Error when the rubric editor autosaves while the focused points input is blank. I'm going to try to get autosave to read blanks as `0`.

**Comment by blerner** [comment]
This looks better -- though I wonder: if an autosave triggers while a particular points field is blank, would that then automatically change the points field to a 0?

**Comment by tmazeika** [comment]
It doesn't change the input while it's focused. There's still a couple of point inputs to fix.

**Comment by tmazeika** [comment]
All points inputs can be autosaved while blank now, except there's a weird JSON schema issue with rubric type points:

```text
Info The property '#/rubrics/questions/0/parts/0/partRubric' of type object did not match one or more of the required schemas. The schema specific errors were:

- anyOf #0:
    -     The property '#/rubrics/questions/0/parts/0/partRubric/choices' of type array did not match any of the required schemas. The schema specific errors were:

    - oneOf #0:
        -         The property '#/rubrics/questions/0/parts/0/partRubric/choices/0' of type object did not match one or more of the required schemas. The schema specific errors were:

        - anyOf #0:
            - The property '#/rubrics/questions/0/parts/0/partRubric/choices/0/type' value "one" did not match one of the following values: all
            - The property '#/rubrics/questions/0/parts/0/partRubric/choices/0' contains additional properties ["points"] outside of the schema when none are allowed
        - anyOf #1:
            - The property '#/rubrics/questions/0/parts/0/partRubric/choices/0/points' of type string did not match the following type: number
            - The property '#/rubrics/questions/0/parts/0/partRubric/choices/0/type' value "one" did not match one of the following values: any
        - anyOf #2:
            - The property '#/rubrics/questions/0/parts/0/partRubric/choices/0/points' of type string did not match the following type: number
        - anyOf #3:
            - The property '#/rubrics/questions/0/parts/0/partRubric/choices/0/type' value "one" did not match one of the following values: none
            - The property '#/rubrics/questions/0/parts/0/partRubric/choices/0' contains additional properties ["points", "description", "choices"] outside of the schema when none are allowed
    - oneOf #1:
        - The property '#/rubrics/questions/0/parts/0/partRubric/choices' of type array did not match the following type: object
- anyOf #1:
    -     The property '#/rubrics/questions/0/parts/0/partRubric/choices' of type array did not match any of the required schemas. The schema specific errors were:

    - oneOf #0:
        -         The property '#/rubrics/questions/0/parts/0/partRubric/choices/0' of type object did not match one or more of the required schemas. The schema specific errors were:

        - anyOf #0:
            - The property '#/rubrics/questions/0/parts/0/partRubric/choices/0/type' value "one" did not match one of the following values: all
            - The property '#/rubrics/questions/0/parts/0/partRubric/choices/0' contains additional properties ["points"] outside of the schema when none are allowed
        - anyOf #1:
            - The property '#/rubrics/questions/0/parts/0/partRubric/choices/0/points' of type string did not match the following type: number
            - The property '#/rubrics/questions/0/parts/0/partRubric/choices/0/type' value "one" did not match one of the following values: any
        - anyOf #2:
            - The property '#/rubrics/questions/0/parts/0/partRubric/choices/0/points' of type string did not match the following type: number
        - anyOf #3:
            - The property '#/rubrics/questions/0/parts/0/partRubric/choices/0/type' value "one" did not match one of the following values: none
            - The property '#/rubrics/questions/0/parts/0/partRubric/choices/0' contains additional properties ["points", "description", "choices"] outside of the schema when none are allowed
    - oneOf #1:
        - The property '#/rubrics/questions/0/parts/0/partRubric/choices' of type array did not match the following type: object
    - The property '#/rubrics/questions/0/parts/0/partRubric/type' value "all" did not match one of the following values: any
    - The property '#/rubrics/questions/0/parts/0/partRubric' did not contain a required property of 'points'
- anyOf #2:
    -     The property '#/rubrics/questions/0/parts/0/partRubric/choices' of type array did not match any of the required schemas. The schema specific errors were:

    - oneOf #0:
        -         The property '#/rubrics/questions/0/parts/0/partRubric/choices/0' of type object did not match one or more of the required schemas. The schema specific errors were:

        - anyOf #0:
            - The property '#/rubrics/questions/0/parts/0/partRubric/choices/0/type' value "one" did not match one of the following values: all
            - The property '#/rubrics/questions/0/parts/0/partRubric/choices/0' contains additional properties ["points"] outside of the schema when none are allowed
        - anyOf #1:
            - The property '#/rubrics/questions/0/parts/0/partRubric/choices/0/points' of type string did not match the following type: number
            - The property '#/rubrics/questions/0/parts/0/partRubric/choices/0/type' value "one" did not match one of the following values: any
        - anyOf #2:
            - The property '#/rubrics/questions/0/parts/0/partRubric/choices/0/points' of type string did not match the following type: number
        - anyOf #3:
            - The property '#/rubrics/questions/0/parts/0/partRubric/choices/0/type' value "one" did not match one of the following values: none
            - The property '#/rubrics/questions/0/parts/0/partRubric/choices/0' contains additional properties ["points", "description", "choices"] outside of the schema when none are allowed
    - oneOf #1:
        - The property '#/rubrics/questions/0/parts/0/partRubric/choices' of type array did not match the following type: object
    - The property '#/rubrics/questions/0/parts/0/partRubric/type' value "all" did not match one of the following values: one
    - The property '#/rubrics/questions/0/parts/0/partRubric' did not contain a required property of 'points'
- anyOf #3:
    - The property '#/rubrics/questions/0/parts/0/partRubric/type' value "all" did not match one of the following values: none
    - The property '#/rubrics/questions/0/parts/0/partRubric' contains additional properties ["choices"] outside of the schema when none are allowed
```

**Comment by blerner** [comment]
Correct -- when a Rubric doesn't have anything in it yet, it schematizes as a list of sub-rubrics, but such a list should not have any points of its own, because they'd be determined by the sub-rubrics.  So blindly filling in `0` for every blank `points` field is slightly overzealous: when rubrics are empty, that's really a `[Maybe Number]` field.

**Comment by blerner** [comment]
This PR got obsoleted by #264, which rewrote everything to do with redux-forms.

**Pull request closed without merging**
