### PR TITLE
Fix fullscreen check

### LINKED ISSUE #155: Developer console is seemingly always open
"Please close the developer console to continue" size checks need fixing.

Test in Chrome and FF.

### PR DESCRIPTION
**Pull request by kylesferrazza**
closes #155 

- [x] chrome
- [ ] firefox (need to test)

### CODE REVIEW

**Comment by kylesferrazza** [comment]
Turns out the innerHeight was coming back one pixel _larger_ than the outer height, at least on my machine...

**Comment by blerner** [comment]
Hooray, math!

**Comment by kylesferrazza** [comment]
Do you see an infinite loop when submitting on firefox? @blerner

**Comment by blerner** [comment]
In Firefox, on this branch: when I first try to start an exam, I get a "general error" (I've seen this a few times, but don't know what it is).  Then when I submitted, yes, it goes into an infinite loop and nearly locked up my whole computer...  It completely locked up Firefox, to the point that I couldn't enter this comment in a separate tab. (Had to restart Firefox before it would resume working.)

**Comment by blerner** [comment]
I couldn't get any profiling information, but looking at the output of `top`, Firefox had suddenly consumed hundreds of gigs of memory, all of a sudden.  Some cycle of event handlers was *also* triggering allocations, which weren't getting released...

**Comment by kylesferrazza** [comment]
Ok, I will keep investigating.

Does your development machine have hundreds of gigs of memory?!

**Comment by blerner** [comment]
Definitely not...I could barely alt-tab, since memory was thrashing.

**Comment by kylesferrazza** [comment]
The problem is unrelated to this branch - happens on `master`.

I will merge this since the sizing check is fixed and open another issue.

**Pull request merged**
